### ISSUE TITLE
Pagination support

### ISSUE THREAD

**Issue by un33k** [tartiflette/tartiflette#317]
[ x ] Feature Request
[ x ] Documentation

If pagination is supported, be nice to include it in documentations. If there is no plan to support it, it'd be nice to provide an example for developers to role their own. Otherwise, let's keep this issue around to track the pagination feature.

**Comment by abusi** [comment]
Hi @un33k, thank you for you for this issue.
Pagination is not a Tartiflette Problem as it can be expressed through SDL and resolver, BUT,
We plan to provide a `tartiflette-plugin-relay` that will help you easily say that you want a field to be paginated automatically.
In order to achieve this, we need some tweak to the engine that I hope to deliver Soon :tm: into the 1.2.x branch of Tartiflette.

Thank you for your interest in this library.

**Comment by abusi** [comment]
Closing this as explained. We'll work on a plugin/cli in order to simplify the writing of SDL/Resolver compliant with pagination.
